name: PR self checker

on:
  pull_request:
    branches: [master, main]
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  self-check:

    name: Run tests
    runs-on: [ubuntu-latest]
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Run check
        run: ./pr-checker.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_CONTAINS_PATTERN: '.{20,}'
          PR_NOT_CONTAINS_PATTERN: 'Why is this PR necessary?'
          PR_COMMENT: |
            Please check description.
            Should be meaningful and not empty.

            Ensure you have added required tags.
          PR_TAGS_MANDATORY: '["change:standard", "change:impactful", "change:emergency", "bug"]'
          SUCCESS_COMMENT: Now this is good PR!

      - name: Unit tests
        run: ./tests/test.sh
