name: PR self checker

on:
  pull_request:
    branches: [master, main]
    types: [opened, edited, synchronize]

jobs:
  self-check:

    name: Check description
    runs-on: [ubuntu-latest]
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Run check
        run: pr-checker.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_CONTAINS_PATTERN: '.{20,}'
#          PULL_REQUEST_NOT_CONTAINS_PATTERN: 'add meaningful description before asking for approval'
#          PULL_REQUEST_NOT_CONTAINS_PATTERN: '.*Why is this PR necessary?.*'
          SUCCESS_EMOJI: '+1'
#          PULL_REQUEST_COMMENT: 'Please check description. \nShould be meaningful and not empty.'
